{% set name = "workflows" %}
{% set version = "2.24.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1dced51329a261e845796c148dc2ebbb1ed1bc69cbd9c941c88d15a786e94a2a
build:
  noarch: python
  number: 0
  entry_points:
    - workflows.validate_recipe = workflows.recipe.validate:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bidict
    - pika
    - python >=3.7
    - setuptools
    - stomp.py >=7.0

test:
  imports:
    - workflows
    - workflows.contrib
    - workflows.frontend
    - workflows.logging
    - workflows.recipe
    - workflows.services
    - workflows.transport
    - workflows.util
  commands:
    - pip check
    - workflows.validate_recipe --help
  requires:
    - pip

about:
  home: https://pypi.python.org/pypi/workflows
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Data processing in distributed environments
  doc_url: https://github.com/DiamondLightSource/python-workflows
  dev_url: https://github.com/DiamondLightSource/python-workflows

extra:
  recipe-maintainers:
    - anthchirp
    - ndevenish
    - rjgildea
