{% set name = "workflows" %}
{% set version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90801b705dbd94333a1585ef4cd55539ee76627c3678610482870ab89da43bf4
build:
  noarch: python
  number: 1
  entry_points:
    - workflows.validate_recipe = workflows.recipe.validate:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bidict
    - pika
    - python >={{ python_min }}
    - setuptools
    - stomp.py >=7.0

test:
  imports:
    - workflows
    - workflows.contrib
    - workflows.frontend
    - workflows.logging
    - workflows.recipe
    - workflows.services
    - workflows.transport
    - workflows.util
  commands:
    - pip check
    - workflows.validate_recipe --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.python.org/pypi/workflows
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Data processing in distributed environments
  doc_url: https://github.com/DiamondLightSource/python-workflows
  dev_url: https://github.com/DiamondLightSource/python-workflows

extra:
  recipe-maintainers:
    - anthchirp
    - ndevenish
    - rjgildea
